import {
  AiOutlineAudit,
  AiOutlineClockCircle,
  AiOutlineInfoCircle,
  AiOutlineLoading3Quarters,
} from 'react-icons/ai';
import {
  BsExclamation,
  BsSpeedometer2,
  FiArrowLeft,
  FiDownloadCloud,
  FiMapPin,
  FiPlayCircle,
  FiRefreshCw,
  FiShare2,
  GiCartwheel,
  IoIosCar,
  IoPaperPlaneOutline,
  MdOutlineGridView,
  TbGridDots,
  TbListDetails,
  TbMapPinOff,
} from 'react-icons/all';
import { BiEnvelope } from 'react-icons/bi';
import {
  FiActivity,
  FiBarChart2,
  FiCalendar,
  FiCrosshair,
  FiDisc,
  FiFileText,
  FiFilter,
  FiFolderPlus,
  FiGlobe,
  FiLayers,
  FiLayout,
  FiSettings,
  FiSliders,
  FiUser,
  FiUserMinus,
  FiUserPlus,
  FiUsers,
} from 'react-icons/fi';
import {
  HiDotsVertical,
  HiLockClosed,
  HiOutlineChat,
  HiOutlineCheck,
  HiOutlineCheckCircle,
  HiOutlineChevronDown,
  HiOutlineChevronLeft,
  HiOutlineChevronRight,
  HiOutlineCloudUpload,
  HiOutlineExclamationCircle,
  HiOutlineEye,
  HiOutlineEyeOff,
  HiOutlineLogout,
  HiOutlineMenu,
  HiOutlineMenuAlt2,
  HiOutlineOfficeBuilding,
  HiOutlinePaperClip,
  HiOutlinePencil,
  HiOutlinePhone,
  HiOutlinePlus,
  HiOutlineQuestionMarkCircle,
  HiOutlineSearch,
  HiOutlineTrash,
  HiOutlineX,
  HiOutlineXCircle,
  HiPencil,
  HiPlay,
  HiQuestionMarkCircle,
} from 'react-icons/hi';
import { TiStar, TiStarHalf, TiStarOutline } from 'react-icons/ti';

import { CAIcon } from './custom/CAIcon';
import { DEIcon } from './custom/DEIcon';
import { ESIcon } from './custom/ESIcon';
import { FRIcon } from './custom/FRIcon';
import { GBIcon } from './custom/GBIcon';
import { ITIcon } from './custom/ITIcon';

export const icons = {
  gbFlag: GBIcon,
  deFlag: DEIcon,
  frFlag: FRIcon,
  itFlag: ITIcon,
  esFlag: ESIcon,
  caFlag: CAIcon,
  clock: AiOutlineClockCircle,
  paperPlane: IoPaperPlaneOutline,
  logout: HiOutlineLogout,
  menu: HiOutlineMenu,
  audit: AiOutlineAudit,
  calendar: FiCalendar,
  loading: AiOutlineLoading3Quarters,
  check: HiOutlineCheck,
  close: HiOutlineX,
  collapse: HiOutlineMenuAlt2,
  globe: FiGlobe,
  upload: HiOutlineCloudUpload,
  attachment: HiOutlinePaperClip,
  question: HiOutlineQuestionMarkCircle,
  questionCircle: HiQuestionMarkCircle,
  users: FiUsers,
  edit: HiOutlinePencil,
  editPencil: HiPencil,
  remove: HiOutlineTrash,
  circleCheck: HiOutlineCheckCircle,
  circleWarning: HiOutlineExclamationCircle,
  circleClose: HiOutlineXCircle,
  company: HiOutlineOfficeBuilding,
  arrowLeft: HiOutlineChevronLeft,
  arrowRight: HiOutlineChevronRight,
  arrowDown: HiOutlineChevronDown,
  arrowBackTo: FiArrowLeft,
  phone: HiOutlinePhone,
  search: HiOutlineSearch,
  threeDotsVertical: HiDotsVertical,
  star: TiStar,
  starHalf: TiStarHalf,
  starOutline: TiStarOutline,
  plus: HiOutlinePlus,
  comment: HiOutlineChat,
  info: AiOutlineInfoCircle,
  envelope: BiEnvelope,
  lockClosed: HiLockClosed,
  dashboard: FiLayout,
  file: FiFileText,
  crossahair: FiCrosshair,
  folderPlus: FiFolderPlus,
  barChart: FiBarChart2,
  sliders: FiSliders,
  activity: FiActivity,
  disc: FiDisc,
  play: HiPlay,
  layers: FiLayers,
  settings: FiSettings,
  user: FiUser,
  filter: FiFilter,
  carInterior: BsSpeedometer2,
  carExterior: IoIosCar,
  carDetail: GiCartwheel,
  carVideo: FiPlayCircle,
  refresh: FiRefreshCw,
  downloadCloud: FiDownloadCloud,
  share: FiShare2,
  list: TbListDetails,
  grid: MdOutlineGridView,
  eye: HiOutlineEye,
  eyeSlashed: HiOutlineEyeOff,
  drag: TbGridDots,
  userPlus: FiUserPlus,
  userMinus: FiUserMinus,
  exclamation: BsExclamation,
  mapPin: FiMapPin,
  mapPinOff: TbMapPinOff,
};
