FROM node:16-alpine AS builder
WORKDIR /styleguide
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . ./
RUN yarn styleguide:build

FROM nginx:1.23.1-alpine AS deploy
COPY --from=builder /styleguide/storybook-static/ /usr/share/nginx/html/
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
