name: Transform Branch Name

on: workflow_dispatch

jobs:
  transform:
    runs-on: ubuntu-latest
    steps:
      - name: Get the branch name
        id: get_branch
        run: |
          TRANSFORMED_BRANCH_NAME=$(echo 'refs/heads/feature/opti_leads' | sed 's|refs/heads/||' | tr '/' '_' | tr '-' '_')
          echo $TRANSFORMED_BRANCH_NAME
          IMAGE_VERSION=$(date +'%Y.%m.%d')-$TRANSFORMED_BRANCH_NAME_nightly.${GITHUB_SHA::7}
          echo "IMAGE_VERSION=IMAGE_VERSION" >> $GITHUB_ENV
      - name: Print transformed name
        run: |
          echo "Transformed branch name: ${IMAGE_VERSION}"
